### ISSUE TITLE
Duplicate Set tilesize when use CPU

### ISSUE THREAD

**Issue by Tohrusky** [media2x/realcugan-ncnn-vulkan-python#2]
>  System:  MacOS M1 arm64
> Cmake Version: 3.25.2
> Vulkan Version: 1.3.239.0
> Python Version: 3.9

### Build 
```
export VULKAN_SDK=/Users/User/VulkanSDK/1.3.239.0/macOS 
mkdir build-arm64 && cd build-arm64
cmake -DUSE_STATIC_MOLTENVK=ON -DCMAKE_OSX_ARCHITECTURES="arm64" \
      -DVulkan_INCLUDE_DIR=/Users/User/VulkanSDK/1.3.239.0/MoltenVK/include \
      -DVulkan_LIBRARY=/Users/User/VulkanSDK/1.3.239.0/MoltenVK/MoltenVK.xcframework/macos-arm64_x86_64/libMoltenVK.a \
      ../src
cmake --build . -j 4
```
When I use GPU, it works well.  
#### BUT WHEN I try to use CPU, it failed.
The same build in official [nihui/realcugan-ncnn-vulkan](https://github.com/nihui/realcugan-ncnn-vulkan), the CPU and GPU also can work. 

I found that 

in [Line 149](https://github.com/media2x/realcugan-ncnn-vulkan-python/blob/master/realcugan_ncnn_vulkan_python/realcugan_ncnn_vulkan.py)
```
        if self._gpuid != -1:
            self._realcugan_object.process(raw_in_image, raw_out_image)
        else:
            self._realcugan_object.tilesize = max(image.width, image.height)
            self._realcugan_object.process_cpu(raw_in_image, raw_out_image)
```
but in
```
def _get_tilesize(self):
        if self._gpuid == -1:
            return 400
```
the tilesize has set   

And in [cugan ncnn main.cpp](https://github.com/nihui/realcugan-ncnn-vulkan/blob/395302c5c70f1bff604c974e92e0a87e45c9f9ee/src/main.cpp), I did not find that.

**Comment by ArchieMeng** [comment]
I didn't reproduce the problem, could you check your source code for the line 149? In my machine(x86_64 Linux), commenting the line
```python
self._realcugan_object.tilesize = max(image.width, image.height)
```
will make CPU mode processing broken on large RGBA images. (Which is the case why this line is needed)

> And in [cugan ncnn main.cpp](https://github.com/nihui/realcugan-ncnn-vulkan/blob/395302c5c70f1bff604c974e92e0a87e45c9f9ee/src/main.cpp), I did not find that.
> 

It used to be 4000 which may set a full image processing without tiling. The corresponding commit is https://github.com/nihui/realcugan-ncnn-vulkan/commit/7f7536dbf754133f4d2cd78610c589cca8643dfc.

And it is the temporary fix for https://github.com/nihui/waifu2x-ncnn-vulkan/issues/186, the crash when up-scaling images larger than tilesize.

**Comment by Tohrusky** [comment]
目前仅在m1 mac下测试了，回头我再试试Win平台

同样的编译指令（未开启openmp）编译nihui和该项目，注释掉149后超分一张1920×1080图片耗时基本一致，warp还快一点（直接os.run，多了读写io等），大概70s左右。

但不注释掉149行时，打断点发现会在该行卡死（好像也能跑出来？不过耗时290s显然异常了hh

不过nihui为什么没有做max(w,h)这个处理呢，直接设定tilesize 400也会导致大图处理崩溃吗😯

PS: cugan ncnn在m1下比 torch慢太多太多辣😡

> 感谢回复，祝您新年快乐！

**Comment by ArchieMeng** [comment]
> 但不注释掉149行时，打断点发现会在该行卡死（好像也能跑出来？不过耗时290s显然异常了hh

如果是这一行卡住的话，可能是tilesize的设置出了什么问题。可以用gdb什么的（MacOS上我不知道用啥）调试下看看具体是binding代码里的哪里挂了。

**Comment by Tohrusky** [comment]
其实是能跑的，只是要卡好久。我自己撸的裤子m1 cpu也都跑的很慢。close了🥳
